### ISSUE TITLE
Clicking 🛑  should trigger the "Time's Up" embed to be sent immediately 

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Trivia-Bot#108]
**Describe the bug**
If a user clicks on 🛑  to stop a game, the "Times's up" embed should be sent immediately, not after the time has run out. This happens in chill modes. In competitive modes, the embed is sent immediately, which is what we want, but the same should happen in chill modes. 

**To Reproduce**
1. Type in `!tfchill`
2. Click on the 🛑  to stop the game 
3. Observe how long it takes for the "Time's Up" embed to be sent
4. Now, type in `!tfcomp` 
5. Click on the 🛑  to stop the game
6. Observe how long it takes for the "Time's Up" embed to be sent

**Expected behavior**
Chill games should behave like competitive games; "Time's up" should be sent immediately. This is necessary because in #104 , functionality has been added to make the time limit per question be based on user request. So, if you say you want time to be 180 seconds (the maximum), then it will take 180 seconds until the game concludes. That shouldn't happen.

**Comment by zuhairnaqi** [comment]
@elenirotsides I have raised the [PR](https://github.com/elenirotsides/Trivia-Bot/pull/113) kindly have a look.
