### ISSUE TITLE
BUG: URGENT - `UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions`

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Trivia-Bot#110]
**Describe the bug**
We are not error handling for missing permissions. The bot craps out when there's a discrepancy in permissions somewhere: `UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions`

**To Reproduce**

I have no idea how this happens, but its been crashing the bot, needs to be taken care of ASAP

**Comment by jalalbmnf** [comment]
Hi there, is this issue still active ?

**Comment by elenirotsides** [comment]
@jalalbmnf Apologies for the delay in my response. The bot hasn't been fully functional for a little while now due to my delay in implementing the required changes mandated by Discord. I'm still working on it, but as I'm working on it, the bot isn't fully functional and so there has been a significant decrease in requests the bot has been getting, so I haven't seen this error lately. However, I'm not sure if this error will continue to persist after it becomes fully functional again, so I'm keeping this issue open until I can verify whether or not it's no longer an issue.

**Comment by jalalbmnf** [comment]
@elenirotsides no problem, thank you for response, maybe then you can close this issue, if it will happen then someone will open issue about this. For now this just confusing us :)
