### ISSUE TITLE
Add a prettier config file to enforce code style

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Trivia-Bot#85]

**Comment by MarcWebDev** [comment]
I could help you with that. What coding style preferences do you want? Tab space size, semicolons yes or no, double quotes or single quotes etc.

**Comment by elenirotsides** [comment]
That would be great thank you so much! I prefer tab width to be 4, semicolons required, and single quotes! I also prefer the print width to be 130. Feel free to add what else you think would be good; I can always make suggestions on your PR. Thanks again, I really appreciate it! @MarcWebDev Lmk if this sounds good and I can mark you as the assignee.

**Comment by MarcWebDev** [comment]
Alr thanks for the informations! Yes you can assign me, I will do the config in some hours.
