### ISSUE TITLE
Implement architecture for rate limit

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Trivia-Bot#90]
**Is your feature request related to a problem? Please describe.**
We need to make sure that we never exceed the rate limit, so implementing some kind of architecture to monitor this will solve this problem.

**Comment by nl32** [comment]
Discord.js handles rate limiting internally so there is no need to implement a separate rate limiting system. This is documented in Discord.js issues [#1054](https://github.com/discordjs/guide/issues/1054), and [#1637](https://github.com/discordjs/discord.js/issues/1637).

**Comment by elenirotsides** [comment]
@nl32 this issue was opened a while before I fully understood the scope of what `discord.js` handles, and I admittedly should have closed this. Thanks!
