### ISSUE TITLE
Make commands case insensitive

### ISSUE THREAD

**Issue by elenirotsides** [elenirotsides/Trivia-Bot#97]
**Describe the bug**
Not really a bug, but an annoyance. Commands should probably be case insensitive.

**Expected behavior**
`!tfchill` should yield the same response as `!tfChill`, for example.

**Additional context**
Probably just need to slap a `.toLowerCase()` on the inputs to solve this problem

**Comment by CTZxVULKAN** [comment]
Could you tell me which file should i will be working on ?

**Comment by elenirotsides** [comment]
Hi @CTZxVULKAN ! I'm so sorry but I think I was looking at the wrong thing when I opened this issue last night. I just checked and the commands are indeed case insensitive, so this issue is no longer needed. I'd love for you to try another issue if you'd like, I have a few open that are good first issues! Again, so sorry for not realizing this yesterday. (For reference, you can see the `.toLowerCase()` method being applied to `cmd` in `src/Events/message/message.js`
